strncmp:,,0
strncmp:abc,abc,3
strncmp:abc,abd,2
strncmp:abc,abd,3
abcd,abc,4
strncmp:abcd,abc,3
strncmp:hello,hellp,5
hello,world,3
Case,case,4
strncmp:prefix,prefixsuffix,6
prefix,prefixsuffix,10
strncmp:foo,bar,0
